package com.mj_solutions.api.project.dto;

public enum ProjectDeveloperRole {
	SUPPORT_OPERATOR,
	DEVELOPER,
	PROJECT_MANAGER,
	WEB_DEVELOPER,
	BACKEND_DEVELOPER,
	FRONTEND_DEVELOPER,
	IOS_DEVELOPER,
	ANDROID_DEVELOPER,
	FULL_STACK_DEVELOPER,
	DEVOPS_ENGINEER
}
