name: CI Dev

on:
  push:
  pull_request:
    branches:
      - 'back'
      - 'app'
      - 'main'
      - 'preprod'

jobs:
  backend:
    name: Backend (API) - Quality & Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: ./mvnw package -DskipTests

      - name: Run tests
        run: ./mvnw test

      - name: Generate test coverage
        run: ./mvnw jacoco:report

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: mj-solutions-api
          path: ./api/target/*.jar

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: ./api/target/site/jacoco/index.html

  shared-install:
    name: Install shared app dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/shared
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install shared dependencies
        run: npm ci

  frontend:
    name: Frontend - Quality & Tests
    runs-on: ubuntu-latest
    needs: shared-install
    defaults:
      run:
        working-directory: ./app/front
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Symlink node_modules for shared
        run: |
          rm -rf ../shared/node_modules
          ln -s ../front/node_modules ../shared/node_modules

      - name: Run tests
        run: npm test

      - name: Build front
        run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: front-build
          path: ./front/dist

  backoffice:
    name: Back-office - Quality & Tests
    runs-on: ubuntu-latest
    needs: shared-install
    defaults:
      run:
        working-directory: ./app/back-office
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install global app dependencies
        run: npm ci
        working-directory: ./app

      - name: Build back-office
        run: npm run build

      - name: Prepare back-office build under /akwaytenpo
        run: |
          mkdir -p ./serve-root/akwaytenpo
          cp -r ./dist/* ./serve-root/akwaytenpo/

      - name: Install static server
        run: npm install -g serve

      - name: Serve back-office build
        run: serve -s ./serve-root -l 4200 --single &

      - name: Wait for back-office to be ready
        run: npx wait-on tcp:4200

      - name: Debug Cypress page
        run: curl -s http://localhost:4200/akwaytenpo/login | head -n 20

      - name: Symlink node_modules for shared
        run: |
          rm -rf ../shared/node_modules
          ln -s ../back-office/node_modules ../shared/node_modules

      - name: Run Cypress E2E back-office tests
        working-directory: ./app
        run: BASE_URL=http://localhost:4200/akwaytenpo npx cypress run --spec 'back-office/e2e/**/*'

      - name: Run unit tests
        run: npm test -- --browsers=ChromeHeadlessNoSandbox --watch=false

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: back-office-build
          path: ./back-office/dist
