name: CI Dev

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  backend:
    name: Backend (API) - Quality & Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # - name: Checkstyle Verification
      #   run: ./mvnw checkstyle:check

      - name: Build project
        run: ./mvnw package -DskipTests

      - name: Run tests
        run: ./mvnw test

      - name: Generate test coverage
        run: ./mvnw jacoco:report

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: mj-solutions-api
          path: ./api/target/*.jar

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: ./api/target/site/jacoco/index.html

  frontend:
    name: Frontend - Quality & Tests
    runs-on: ubuntu-latest
    needs: backend
    defaults:
      run:
        working-directory: ./app/front
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build front (optionnel)
        run: npm run build

      - name: Upload build (optionnel)
        uses: actions/upload-artifact@v4
        with:
          name: front-build
          path: ./front/dist

  backoffice:
    name: Back-office - Quality & Tests
    runs-on: ubuntu-latest
    needs: backend
    defaults:
      run:
        working-directory: ./app/back-office
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --browsers=ChromeHeadlessNoSandbox --watch=false

      - name: Build back-office (optionnel)
        run: npm run build

      - name: Upload build (optionnel)
        uses: actions/upload-artifact@v4
        with:
          name: back-office-build
          path: ./back-office/dist